In [1]:
import numpy as np 

In [2]:
np.__version__

'1.26.4'

In [3]:
# list , array 
lst = [1,2,3,4,5,5,6,6]
arr =np.array(lst)

In [4]:
arr 

array([1, 2, 3, 4, 5, 5, 6, 6])

In [5]:
arr =np.array([1,2,3,4,5,5,6,6,7,8,8])

In [6]:
arr 

array([1, 2, 3, 4, 5, 5, 6, 6, 7, 8, 8])

In [7]:
lst = [1,2,3,4,5,5,6,6]
print("type of list ", type(lst))
arr =np.array(lst)
print(arr)
print("types of array ",type(arr))

type of list  <class 'list'>
[1 2 3 4 5 5 6 6]
types of array  <class 'numpy.ndarray'>


In [8]:
arr =np.array(list(range(1,21)))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [9]:
arr =np.arange(1,21)
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(100)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.zeros((5,10))  ## 5 row and 10 coloums 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
arr =np.linspace(1,10,5)
arr 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
# 1d array convert into 2d array 
arr =np.arange(0,30)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [19]:
arr.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [20]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [ ]:
arr =np.random.randint(1,5,9)  
arr 

array([3, 1, 1, 4, 4, 4, 4, 4, 1])

In [22]:
arr =np.random.randint(1,5,(3,3))  
arr 

array([[2, 1, 4],
       [2, 4, 1],
       [1, 4, 3]])

In [23]:
arr =np.random.random(10)
arr 

array([0.69712217, 0.37866277, 0.63895385, 0.79979224, 0.08095165,
       0.25294553, 0.61320512, 0.7894474 , 0.66951743, 0.35900176])

In [25]:
arr =np.random.random((5,10))
arr 

array([[0.58288615, 0.45420126, 0.78879729, 0.60645625, 0.17529428,
        0.28706278, 0.44589028, 0.00382721, 0.55100942, 0.9346878 ],
       [0.86434753, 0.32765037, 0.44497185, 0.13661541, 0.55788486,
        0.74024963, 0.52909719, 0.88128114, 0.90641753, 0.91003164],
       [0.69383497, 0.61839699, 0.96515082, 0.98764918, 0.04291224,
        0.17258539, 0.7580345 , 0.24909147, 0.05137171, 0.17950846],
       [0.12276945, 0.63958078, 0.72798714, 0.84677317, 0.27765162,
        0.09044676, 0.38580978, 0.13160688, 0.267817  , 0.3756258 ],
       [0.0480869 , 0.08138647, 0.58112309, 0.4519136 , 0.57389741,
        0.4268054 , 0.91136999, 0.69487111, 0.3904058 , 0.11692396]])

In [26]:
arr =np.arange(60).reshape(12,5)
arr 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [27]:
print("shape of array : - ",arr.shape)
print("size of array", arr.size)
print("data types :- ",arr.dtype)
print("number of dimension ",arr.ndim)

shape of array : -  (12, 5)
size of array 60
data types :-  int32
number of dimension  2


In [28]:
arr 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
arr.flatten()       

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [30]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [32]:
arr.shape

(12, 5)

In [34]:
arr.T.shape

(5, 12)

In [35]:
arr =np.arange(30)

In [36]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [37]:
arr[12]

12

In [38]:
arr[20]


20

In [39]:
arr[0:12]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
arr[0]=100

In [43]:
arr 

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [44]:
arr =np.arange(60).reshape(12,5)

In [47]:
arr[1,3:5]

array([8, 9])

In [46]:
arr[1,1]

6

In [48]:
arr 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [49]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [51]:
arr[1,1]=100

In [52]:
arr 

array([[  0,   1,   2,   3,   4],
       [  5, 100,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [53]:
arr[11,4]

59

In [55]:
arr[-1][-1]

59

In [56]:
arr[11][-1]

59

In [57]:
arr[-1,-1]

59

In [58]:
arr =np.array(np.arange(225).reshape(5,15,3))

In [60]:
arr.ndim, arr.shape, arr.size, arr.dtype

(3, (5, 15, 3), 225, dtype('int32'))

In [61]:
arr 

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [66]:
arr[0,2:,2]

array([ 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [67]:
arr[0, 3:5]

array([[ 9, 10, 11],
       [12, 13, 14]])

In [68]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [70]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [72]:
arr[0,1,1] = 1000

In [73]:
arr[0,1,1]

1000

In [74]:
arr =np.array([1,5,6,9,2,3])

In [76]:
arr.sort()

In [78]:
arr

array([1, 2, 3, 5, 6, 9])

In [79]:
arr+2

array([ 3,  4,  5,  7,  8, 11])

In [80]:
arr-2

array([-1,  0,  1,  3,  4,  7])

In [81]:
arr*2

array([ 2,  4,  6, 10, 12, 18])

In [82]:
arr/2

array([0.5, 1. , 1.5, 2.5, 3. , 4.5])

In [83]:
arr1 = np.array([1,2,3,5])
arr2 = np.array([1,6,3,5])


In [86]:
# arr1+arr2
# arr1*arr2
arr1-arr2

array([ 0, -4,  0,  0])